  server:
    servlet:
      context-path: /cliente/api

  spring:
    datasource:
      url: jdbc:h2:mem:mydb
      username: sa
      password: aa
      driverClassName: org.h2.Driver

    h2:
      console:
        enabled: true
        path: /h2-console


